### ISSUE TITLE
make_examples_somatic fails due to invalid reference base

### ISSUE THREAD

**Issue by byoo** [google/deepsomatic#31]
Hello, I got an error in running Deepsomatic on PacBio Hifi reads in a tumor normal mode. Could you help troubleshoot the issue?

Log: [make_examples_somatic.log](https://github.com/user-attachments/files/17781121/make_examples_somatic.log)

```
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_6yev779j/runfiles/com_google_deepvariant/deepvariant/make_examples_somatic.py", line 321, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_6yev779j/runfiles/absl_py/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_6yev779j/runfiles/absl_py/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_6yev779j/runfiles/com_google_deepvariant/deepvariant/make_examples_somatic.py", line 311, in main
    make_examples_core.make_examples_runner(options)
  File "/tmp/Bazel.runfiles_6yev779j/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 3043, in make_examples_runner
    region_processor.process(region, region_n)
  File "/tmp/Bazel.runfiles_6yev779j/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 2084, in process
    candidates_by_sample, gvcfs_by_sample = self.candidates_in_region(
  File "/tmp/Bazel.runfiles_6yev779j/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 2480, in candidates_in_region
    candidates[role], gvcfs[role] = sample.variant_caller.calls_and_gvcfs(
  File "/tmp/Bazel.runfiles_6yev779j/runfiles/com_google_deepvariant/deepvariant/variant_caller.py", line 419, in calls_and_gvcfs
    gvcfs = list(
  File "/tmp/Bazel.runfiles_6yev779j/runfiles/com_google_deepvariant/deepvariant/variant_caller.py", line 313, in make_gvcfs
    for key, combinable in itertools.groupby(
  File "/tmp/Bazel.runfiles_6yev779j/runfiles/com_google_deepvariant/deepvariant/variant_caller.py", line 314, in <genexpr>
    (with_gq_and_likelihoods(sc) for sc in allele_count_summaries),
  File "/tmp/Bazel.runfiles_6yev779j/runfiles/com_google_deepvariant/deepvariant/variant_caller.py", line 289, in with_gq_and_likelihoods
    raise ValueError(
ValueError: Invalid reference base=> found during gvcf calculation
parallel: This job failed:
/opt/deepvariant/bin/make_examples_somatic --mode calling --ref /analysis/cloud_projects/research/reference/GRCh38/human_GRCh38_no_alt_analysis_set.fa --reads_tumor /analysis/projects/carbon/GRCh38/pacbio/PB-001-AML-T/whatshap/PB-001-AML-T.GRCh38.deepvariant.haplotagged.bam --reads_normal /analysis/projects/carbon/GRCh38/pacbio/PB-001-AML-N/whatshap/PB-001-AML-N.GRCh38.deepvariant.haplotagged.bam --examples '/mnt/scratch/byoo/intermediate_results_dir/make_examples_somatic.tfrecord@56.gz' --checkpoint /opt/models/deepsomatic/pacbio --alt_aligned_pileup diff_channels --gvcf '/mnt/scratch/byoo/intermediate_results_dir/gvcf.tfrecord@56.gz' --min_mapping_quality 5 --parse_sam_aux_fields --partition_size 25000 --phase_reads --pileup_image_width 99 --norealign_reads --sample_name_normal PB-001-AML-N --sample_name_tumor PB-001-AML-T --sort_by_haplotypes --track_ref_reads --trim_reads_for_pileup --vsc_max_fraction_indels_for_non_target_sample 0.5 --vsc_max_fraction_snps_for_non_target_sample 0.5 --vsc_min_count_snps 1 --vsc_min_fraction_indels 0.1 --vsc_min_fraction_snps 0.02 --task 46
```

**Comment by akolesnikov** [comment]
The program could not parse the reference file. There was an invalid base '>' while processing the reference.

**Comment by byoo** [comment]
Yes, it looks correct that make_examples_somatic couldn't parse the reference properly. It seems to have something to do with Azure's blobfuse. make_examples_somatic doesn't look to use the reference in Azure's blobfuse mount. Moving the reference to a NFS mount resolved the issue.
