### ISSUE TITLE
ONT failed

### ISSUE THREAD

**Issue by DayTimeMouse** [google/deepsomatic#33]
Hi,

I used deepsomatic(v.1.6.1) to call somatic mutations using ONT reads. But the process failed.
My parameter is --model_type=ONT_R104
**errors:**
```
2024-12-01 05:55:20.276827: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
I1201 05:55:22.716089 140312890513216 run_deepsomatic.py:520] Creating a directory for intermediate results in /output/intermediate_results_dir
I1201 05:55:22.716460 140312890513216 run_deepsomatic.py:689] Creating a directory for logs in /output/logs
Traceback (most recent call last):
  File "/opt/deepvariant/bin/deepsomatic/run_deepsomatic.py", line 721, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/deepsomatic/run_deepsomatic.py", line 692, in main
    commands_logfiles = create_all_commands_and_logfiles(intermediate_results_dir)
  File "/opt/deepvariant/bin/deepsomatic/run_deepsomatic.py", line 624, in create_all_commands_and_logfiles
    model_ckpt = get_model_ckpt(_MODEL_TYPE.value, _CUSTOMIZED_MODEL.value)
  File "/opt/deepvariant/bin/deepsomatic/run_deepsomatic.py", line 563, in get_model_ckpt
    return MODEL_TYPE_MAP[model_type]
KeyError: 'ONT_R104'
```

Best regards.

**Comment by kishwarshafin** [comment]
@DayTimeMouse can you please share the full command line? Also in DeepSomatic, the model type is ONT and not ONT_R104 like deepvariant. Please see here: https://github.com/google/deepsomatic/blob/r1.7/docs/deepsomatic-case-study-ont.md

**Comment by DayTimeMouse** [comment]
Yes, I used `--model_type=ONT` firstly, but get the error:
```
2024-12-02 02:22:43.265989: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
FATAL Flags parsing error: flag --model_type=ONT: value should be one of <WGS|ONT_R104|PACBIO>
Pass --helpshort or --helpfull to see help on flags.
```
So I set --model_type=ONT_R104.

There is my full command line:
```
OUTPUT_DIR="/home/workdir/deepsomatic/ds_output"
INPUT_DIR="/home/workdir/deepsomatic/ds_input"
mkdir -p "${OUTPUT_DIR}"
BIN_VERSION="1.6.1"
docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}:/output" \
  google/deepsomatic:"${BIN_VERSION}" \
  run_deepsomatic \
  --model_type=ONT \
  --ref=/input/chm13v2.0.fa \
  --reads_normal=/input/ont_normal_minimap2.bam \
  --reads_tumor=/input/ont_tumor_minimap2.bam \
  --output_vcf=/output/somatic_output_vcf.gz \
  --output_gvcf=/output/somatic_output_g.vcf.gz \
  --sample_name_tumor="tumor" \
  --sample_name_normal="normal" \
  --num_shards=30 \
  --logging_dir=/output/logs \
  --intermediate_results_dir=/output/intermediate_results_dir
```

**Comment by DayTimeMouse** [comment]
Hi [kishwarshafin](https://github.com/kishwarshafin),

I can't pull image of v.1.7.0, could you send me a singularity sif file for me, then I can used it via singularity.

Thanks in advance.

**Comment by kishwarshafin** [comment]
@DayTimeMouse you can always pull dockers to run singulairy:

```bash
singularity run -B /usr/lib/locale/:/usr/lib/locale/ \
docker://google/deepsomatic:"1.7.0" \
run_deepsomatic ...
```
